version: '3.8'

services:
  api:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - TYPEORM_DATABASE=/app/data/db.sqlite
      - BAN_API_URL=https://api-adresse.data.gouv.fr/search
      - GEORISQUES_API_URL=https://georisques.gouv.fr/api/v1/resultats_rapport_risque
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8000/api/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
